[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "solady/=lib/solady/src/",
    "seismic-std-lib/=src/seismic-std-lib/",
]
# via-ir support was added in https://github.com/SeismicSystems/seismic-solidity/pull/204
# However it is considered experimental and less safe, so we keep it false by default.
via_ir = false

[profile.via-ir]
via_ir = true
# This (temporary) additional flag is required to make sure ssolc users 
# are aware that the via-ir pipeline is experimental.
unsafe_via_ir = true

[profile.ssolc-local]
solc = "../../seismic-solidity/build/solc/solc"
